# Generated by Django 5.1.4 on 2025-04-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('piece', 'Piece'), ('packet', 'Packet'), ('set', 'set')], default='', max_length=10),
        ),
    ]
